# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1 on 2026-08-22 07:33

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import pgvector.django.halfvec
import pgvector.django.indexes
from django.conf import settings
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Extensions first — the pgvector image ships them; the role needs CREATE privilege (superuser in dev).
        VectorExtension(),
        TrigramExtension(),
        UnaccentExtension(),
        migrations.CreateModel(
            name="Fingerprint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("pim_product", "PIM product"), ("atlas_source_product", "Atlas source product")],
                        max_length=32,
                    ),
                ),
                ("ref", models.CharField(max_length=255)),
                ("gtin14", models.CharField(blank=True, db_index=True, default="", max_length=14)),
                ("gtin_trusted", models.BooleanField(default=False)),
                ("brand_norm", models.CharField(blank=True, default="", max_length=255)),
                ("mpn_norm", models.CharField(blank=True, default="", max_length=255)),
                ("name_norm", models.TextField(blank=True, default="")),
                (
                    "name_tokens",
                    django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list),
                ),
                ("pack_qty", models.PositiveIntegerField(blank=True, null=True)),
                ("color", models.CharField(blank=True, default="", max_length=64)),
                ("size", models.CharField(blank=True, default="", max_length=64)),
                ("weight", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("width", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("height", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("deep", models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ("phash", models.BigIntegerField(blank=True, null=True)),
                ("dhash", models.BigIntegerField(blank=True, null=True)),
                ("image_vec", pgvector.django.halfvec.HalfVectorField(blank=True, dimensions=1152, null=True)),
                ("vec_model", models.CharField(blank=True, default="", max_length=64)),
                ("image_sha1", models.CharField(blank=True, default="", max_length=40)),
                ("source_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["brand_norm", "mpn_norm"], name="lookup_fp_brand_mpn_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["name_norm"], name="lookup_fp_name_trgm_idx", opclasses=["gin_trgm_ops"]
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["image_vec"],
                        m=16,
                        name="lookup_fp_image_vec_hnsw_idx",
                        opclasses=["halfvec_cosine_ops"],
                    ),
                ],
                "constraints": [models.UniqueConstraint(fields=("kind", "ref"), name="uq_lookup_fingerprint_kind_ref")],
            },
        ),
        migrations.CreateModel(
            name="DedupDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("query", models.JSONField(blank=True, default=dict)),
                (
                    "candidate_kind",
                    models.CharField(
                        choices=[("pim_product", "PIM product"), ("atlas_source_product", "Atlas source product")],
                        max_length=32,
                    ),
                ),
                ("candidate_ref", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("features", models.JSONField(blank=True, default=list)),
                (
                    "decision_auto",
                    models.CharField(
                        choices=[("match", "Match"), ("review", "Review"), ("no_match", "No match")], max_length=16
                    ),
                ),
                (
                    "decision_human",
                    models.CharField(
                        blank=True,
                        choices=[("accepted", "Accepted"), ("rejected", "Rejected")],
                        default="",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("api_check", "API check"),
                            ("create_hook", "PIM create hook"),
                            ("proposal", "Enrichment proposal"),
                        ],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["candidate_kind", "candidate_ref"], name="lookup_dec_candidate_idx"),
                    models.Index(fields=["-created_at"], name="lookup_dec_created_idx"),
                ],
            },
        ),
    ]
