# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.6 on 2026-08-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_lookup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dedupdecision",
            name="subject_ref",
            field=models.CharField(blank=True, db_index=True, default="", max_length=255),
        ),
    ]
