# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.1 on 2026-08-24 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_lookup", "0002_dedupdecision_subject_ref"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dedupdecision",
            name="source",
            field=models.CharField(
                choices=[
                    ("api_check", "API check"),
                    ("create_hook", "PIM create hook"),
                    ("proposal", "Enrichment proposal"),
                    ("lookup_eval", "Calibration eval (lookup_eval)"),
                ],
                max_length=16,
            ),
        ),
    ]
