# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.6 on 2026-08-24 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("django_lookup", "0003_alter_dedupdecision_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fingerprint",
            name="dhash",
        ),
    ]
